#' @title Linker carry calculations
#'
#' @description Returns the carry of an inflation-linked bond given either a price or yield, for 1mn local currency nominal. Using either
#'       an ISIN with the database (\code{_db}), an ISIN/security name (\code{_bloomberg}), or with the full set of information about the bond. 
#'       One of either a real yield or price is required in order to work out the values. 
#' 
#' @name linker_carry_func
#'
#' @param bond_ISIN character, specifying bond ISIN of an inflation linked bond, e.g. \code{"US912810SV17"}, must be in the database 
#' @param security character, can be a bond ISIN or security name in bloomberg format e.g. \code{"TII 0.375 07/15/27"}
#' @param projected_inflation_curve data.table, curve of projected inflation with columns \code{date} and \code{proj_infl}
#'    , eg can be generated by \link[InflationTools]{implied_proj_inflation_curve} 
#' @param carry_days numeric, the number of days over which to calculate the carry      
#' @param real_price numeric, clean price of bond at reference date
#' @param real_yield numeric, real yield of bond at reference date in percent
#' @param ref_date date, trade or calculation date, regular settle is assumed in \code{_db} functions
#' @param reference_cpi numeric, the CPI index of the bond at issue, sometimes also called "base CPI"
#' @param inflation_lag numeric, the lag in months that instrument has to the inflation index
#' @param principal_floor numeric, the percentage floor of the principal, eg 100 is floored at par
#' @param coupon_floor numeric, the percentage floor of the coupon, eg 0 is not floored
#' @param lm_database_path Path class character to list management database
#' @param infl_database_path Path class character to inflation database
#' @param maturity_date date, the date of the maturity ie final cashflow 
#' @param coupon numeric, the coupon in percent to be paid at regular intervals
#' @param payment_frequency numeric, the number of times per year the coupon is to be paid
#' @param settle_convention numeric, the days until the instrument will be settled
#' @param day_count character, the day count convention of the instrument. Can currently only be \code{"ACT/ACT"}.
#'
#' @return list of carry statistics. \code{carry} is the actual carry for the period, while \code{carry_dv01} is 
#'     the carry per unit of DV01  (inflation). 
#'
#' @examples
#' 
#' linker_carry_yield(real_yield = -2.56,
#'        carry_days = 30,
#'        projected_inflation_curve = exampleUSInflationCurve,
#'        reference_cpi = 269.59839,
#'        inflation_lag = 3,
#'        principal_floor = 100,
#'        coupon_floor = 0,
#'        maturity_date = as.Date("2023-01-15"),
#'        coupon = 0.125,
#'        payment_frequency = 2
#'        )
#' \dontrun{ 
#'    linker_carry_bloomberg(security = "US912810SV17",
#'          carry_days = 30,
#'          projected_inflation_curve = exampleUSInflationCurve
#'    )  
#' }
#' 
#' @importFrom lubridate %m+%
NULL


#' @rdname linker_carry_func
#' @export
linker_carry_yield <- function(real_yield,
                               carry_days = 30,
                               projected_inflation_curve,
                               reference_cpi,
                               inflation_lag,
                               principal_floor,
                               coupon_floor,
                               maturity_date,
                               coupon,
                               payment_frequency,
                               ref_date = Sys.Date(),
                               settle_convention = 1,
                               day_count = "ACT/ACT"){
  
  
  carry_date <- ref_date + lubridate::days(carry_days)
  
  initial_proceeds <- InflationTools::linker_proceeds_yield(real_yield,
                                                            projected_inflation_curve,
                                                            reference_cpi,
                                                            inflation_lag,
                                                            maturity_date,
                                                            coupon,
                                                            payment_frequency,
                                                            ref_date = ref_date,
                                                            settle_convention = settle_convention,
                                                            day_count = day_count)
  
  new_proceeds <- InflationTools::linker_proceeds_yield(real_yield,
                                                        projected_inflation_curve,
                                                        reference_cpi,
                                                        inflation_lag,
                                                        maturity_date,
                                                        coupon,
                                                        payment_frequency,
                                                        ref_date = carry_date,
                                                        settle_convention = settle_convention,
                                                        day_count = day_count)
  
  
  cashflow_table <- InflationTools::cashflow_table(maturity_date = maturity_date,
                                                   coupon = coupon,
                                                   payment_frequency = payment_frequency,
                                                   ref_date = ref_date,
                                                   settle_convention = settle_convention,
                                                   day_count = day_count)
  
  linker_cashflow_table <- InflationTools::linker_cashflow_table(cashflow_table = cashflow_table,
                                                                 projected_inflation_curve = projected_inflation_curve,
                                                                 reference_cpi = reference_cpi,
                                                                 ref_date = ref_date,
                                                                 settle_convention = settle_convention,
                                                                 inflation_lag = inflation_lag,
                                                                 principal_floor = principal_floor,
                                                                 coupon_floor = coupon_floor)
  
  coupon_proceeds <- linker_cashflow_table %>%
    dplyr::filter(cashflow_date >= ref_date,
                  cashflow_date < carry_date) %>%
    dplyr::summarise(coupon_pro = sum(adjusted_interest)) %>%
    dplyr::pull(coupon_pro)
  
  cash_carry <- new_proceeds - initial_proceeds + coupon_proceeds
  
  
  
  mac_dur <- InflationTools::duration_mac_inflation(linker_cashflow_table,
                                                    real_yield,
                                                    payment_frequency)
  
  mod_dur <- mac_dur / (1 + (real_yield / (payment_frequency * 100)))
  
  real_accrued <- InflationTools::real_accrued(cashflow_table)
  real_price <- InflationTools::real_price(cashflow_table, real_yield, payment_frequency, real_accrued) 
  current_index_value <- InflationTools::interpolate_inflation_curve(projected_inflation_curve,
                                                                     ref_date = ref_date,
                                                                     inflation_lag = inflation_lag,
                                                                     settle_convention = settle_convention,
                                                                     round_5 = TRUE)
  
  current_index_ratio <- round((current_index_value / reference_cpi), 5)
  
  dv01_nom <- (mod_dur * real_price)  
  
  dv01_inf <- dv01_nom * current_index_ratio
  
  bp_dv01 <- cash_carry / dv01_inf
  
  output <- list(carry = cash_carry,
                 carry_dv01 = bp_dv01)
  
  return(output)
  
}






#' @rdname linker_carry_func
#' @export
linker_carry_bloomberg <- function(security, 
                                   projected_inflation_curve, 
                                   carry_days, 
                                   principal_floor = 100, 
                                   cpn_floor = 0) {
  
  if (!is.character(security)) {
    futile.logger::flog.error("security must be a string, either the bonds ISIN or security name")
  }
  
  if (!is.numeric(carry_days)) {
    futile.logger::flog.error("carry_days must be numeric")
  }
  
  if (!is.numeric(principal_floor)) {
    futile.logger::flog.error("principal_floor must be numeric")
  }
  
  if (!is.numeric(cpn_floor)) {
    futile.logger::flog.error("cpn_floor must be numeric")
  }
  
  fields_static <- c(
    "MATURITY",
    "CPN_FREQ",
    "CPN",
    "YLD_YTM_MID",
    "YAS_ASW_SPREAD",
    "INFLATION_ADJ_RISK_MID",
    "INFLATION_ADJ_DUR_MID",
    "IDX_RATIO",
    "BASE_CPI",
    "REFERENCE_CPI",
    "REFERENCE_INDEX",
    "INFLATION_LAG"
  )
  
  linker_static <-
    FIRVr::bloomberg_query_static(
      securities =  paste0(security, " Govt"),
      fields = c(fields_static),
      tidy_data = FALSE
    )
  
  if(nrow(linker_static) > 0){
    
    carry <- InflationTools::linker_carry_yield(
      real_yield = linker_static$YLD_YTM_MID,
      carry_days = carry_days,
      projected_inflation_curve = projected_inflation_curve,
      reference_cpi = linker_static$REFERENCE_CPI,
      inflation_lag = linker_static$INFLATION_LAG,
      principal_floor = principal_floor,
      coupon_floor = cpn_floor,
      maturity_date = linker_static$MATURITY,
      coupon = linker_static$CPN,
      payment_frequency = linker_static$CPN_FREQ
    )
    
    return(carry)
    
  }else{
    
    futile.logger::flog.error("Error retrieving data from Bloomberg")
    
  }
  
}
