
#' @title Linker statistics calculations 
#'
#' @description Returns information on an inflation-linked bond given either a price or yield, for 1mn local currency nominal. Using either
#'       an ISIN with the database (\code{_db}) or with the full set of information about the bond. 
#'       One of either a real yield or price is required in order to work out the risk values. 
#' 
#' @name linker_info_func
#'
#' @param bond_ISIN character, specifying bond ISIN of an inflation linked bond, e.g. \code{"US912810SV17"}, must be in the database 
#' @param projected_inflation_curve data.table, curve of projected inflation with columns \code{date} and \code{proj_infl}
#'    , eg can be generated by \link[InflationTools]{implied_proj_inflation_curve} 
#' @param real_price numeric, clean price of bond at reference date
#' @param real_yield numeric, real yield of bond at reference date in percent
#' @param ref_date date, trade or calculation date, regular settle is assumed in \code{_db} functions
#' @param reference_cpi numeric, the CPI index of the bond at issue, sometimes also called "base CPI"
#' @param inflation_lag numeric, the lag in months that instrument has to the inflation index
#' @param principal_floor numeric, the percentage floor of the principal, eg 100 is floored at par
#' @param coupon_floor numeric, the percentage floor of the coupon, eg 0 is not floored
#' @param lm_database_path Path class character to list management database
#' @param infl_database_path Path class character to inflation database
#' @param maturity_date date, the date of the maturity ie final cashflow 
#' @param coupon numeric, the coupon in percent to be paid at regular intervals
#' @param payment_frequency numeric, the number of times per year the coupon is to be paid
#' @param settle_convention numeric, the days until the instrument will be settled
#' @param day_count character, the day count convention of the instrument. Can currently only be \code{"ACT/ACT"}.
#'
#' @return list of bond statistics
#'
#' @examples
#' \dontrun{
#'    linker_info_db(bond_ISIN = "US912810SV17", 
#'                projected_inflation_curve = exampleUSInfaltionCurve, 
#'                real_yield = -0.3)
#'    linker_info_db(bond_ISIN = "US912810SV17", 
#'                projected_inflation_curve = exampleUSInfaltionCurve, 
#'                real_price = 120)
#' }
#' @importFrom lubridate %m+%
NULL


#' @rdname linker_info_func
#' @export
linker_info_yield <- function(real_yield,
                              projected_inflation_curve,
                              reference_cpi,
                              inflation_lag,
                              principal_floor,
                              coupon_floor,
                              maturity_date,
                              coupon,
                              payment_frequency,
                              ref_date = Sys.Date(),
                              settle_convention = 1,
                              day_count = "ACT/ACT"){
  
  if(ref_date >= maturity_date){
    futile.logger::flog.error("Reference date is after maturity")
    return(list())
  }
  
  cashflow_table <- InflationTools::cashflow_table(maturity_date = maturity_date,
                                                   coupon = coupon,
                                                   payment_frequency = payment_frequency,
                                                   ref_date = ref_date,
                                                   settle_convention = settle_convention,
                                                   day_count = day_count)
  
  linker_cashflow_table <- InflationTools::linker_cashflow_table(cashflow_table = cashflow_table,
                                                                 projected_inflation_curve = projected_inflation_curve,
                                                                 reference_cpi = reference_cpi,
                                                                 ref_date = ref_date,
                                                                 settle_convention = settle_convention,
                                                                 inflation_lag = inflation_lag,
                                                                 principal_floor = principal_floor,
                                                                 coupon_floor = coupon_floor)
  
  real_accrued <- InflationTools::real_accrued(cashflow_table)
  
  real_price <- InflationTools::real_price(cashflow_table, real_yield, payment_frequency, real_accrued) 
  
  current_index_value <- InflationTools::interpolate_inflation_curve(projected_inflation_curve,
                                                                      ref_date = ref_date,
                                                                      inflation_lag = inflation_lag,
                                                                      settle_convention = settle_convention,
                                                                      round_5 = TRUE)
  
  current_index_ratio <- round((current_index_value / reference_cpi), 5)
  
  actual_accrued <- real_accrued * current_index_ratio
  
  principal <- (real_price *  current_index_ratio * 10000)
  
  proceeds <- principal + actual_accrued
  
  output_cashflow_table <- linker_cashflow_table %>%
    dplyr::select(cashflow_date, adjusted_cashflow) %>%
    dplyr::rename(date = cashflow_date,
                  cashflow = adjusted_cashflow)
  
  
  
  real_yield_sa <- InflationTools::seasonally_adjusted_real_yield(linker_cashflow_table,
                                                                  real_price,
                                                                  payment_frequency,
                                                                  real_accrued)
  
  nominal_yield <- InflationTools::nominal_equivalent_yield(linker_cashflow_table,
                                                            real_price,
                                                            payment_frequency,
                                                            real_accrued, 
                                                            principal)
  
  mac_dur <- InflationTools::duration_mac_inflation(linker_cashflow_table,
                                                    real_yield,
                                                    payment_frequency)
  
  mod_dur <- mac_dur / (1 + (real_yield / (payment_frequency * 100)))
  
  dv01_nom <- (mod_dur * real_price)  
  
  dv01_inf <- dv01_nom * current_index_ratio
  
  convexity <- InflationTools::convexity_inflation(linker_cashflow_table,
                                                   real_yield,
                                                   payment_frequency)
  
  inflation_to_mat <- ((linker_cashflow_table$proj_infl[nrow(linker_cashflow_table)] / current_index_value) ^ 
                         (payment_frequency / linker_cashflow_table$discount_period_fraction[nrow(linker_cashflow_table)])
                       ) - 1  
  
  ie01 <- mac_dur * real_price * (1 / (1 + inflation_to_mat))
  
  output_list <- list(real_yield_nsa = real_yield,
                      real_yield_sa = real_yield_sa,
                      real_price = real_price,
                      nominal_equivalent_yield = nominal_yield,
                      real_accured =  real_accrued %>% round(2),
                      actual_accrued = actual_accrued %>% round(2),
                      principal = principal %>% round(2),
                      proceeds = proceeds %>% round(2),
                      current_index_value = current_index_value,
                      current_index_ratio = current_index_ratio,
                      cashflows = output_cashflow_table,
                      macaulay_duration = mac_dur,
                      modified_duration = mod_dur,
                      dv01_nom = dv01_nom,
                      dv01_inf = dv01_inf,
                      convexity = convexity,
                      ie01 = ie01)
  
  return(output_list)
  
}




#' @rdname linker_info_func
#' @export
linker_info <- function(real_yield = NULL,
                        real_price = NULL,
                        projected_inflation_curve,
                        reference_cpi,
                        inflation_lag,
                        principal_floor,
                        coupon_floor,
                        maturity_date,
                        coupon,
                        payment_frequency,
                        ref_date = Sys.Date(),
                        settle_convention = 1,
                        day_count = "ACT/ACT"){
  
  if (is.null(real_yield) == is.null(real_price)) {
    futile.logger::flog.error("One and only one of real_yield and real_price can be defined.")
  }
  
  if (!is.numeric(reference_cpi)) {
    futile.logger::flog.error("Reference CPI must be a numeric value")
  }
  
  if (!is.numeric(inflation_lag)) {
    futile.logger::flog.error("Inflation lag must be a numeric value")
  }
  
  if (!is.numeric(coupon)) {
    futile.logger::flog.error("Coupon lag must be a numeric value")
  }
  
  if(is.null(real_yield)){info <- InflationTools::linker_info_price(real_price = real_price,
                                                    projected_inflation_curve = projected_inflation_curve,
                                                    reference_cpi = reference_cpi,
                                                    inflation_lag = inflation_lag,
                                                    principal_floor = principal_floor,
                                                    coupon_floor = coupon_floor,
                                                    maturity_date = maturity_date,
                                                    coupon = coupon,
                                                    payment_frequency = payment_frequency,
                                                    ref_date = ref_date,
                                                    settle_convention = settle_convention,
                                                    day_count = day_count)}
  
  if(is.null(real_price)){info <- InflationTools::linker_info_yield(real_yield = real_yield,
                                                    projected_inflation_curve = projected_inflation_curve,
                                                    reference_cpi = reference_cpi,
                                                    inflation_lag = inflation_lag,
                                                    principal_floor = principal_floor,
                                                    coupon_floor = coupon_floor,
                                                    maturity_date = maturity_date,
                                                    coupon = coupon,
                                                    payment_frequency = payment_frequency,
                                                    ref_date = ref_date,
                                                    settle_convention = settle_convention,
                                                    day_count = day_count)}
  
  return(info)
  
}


#' @rdname linker_info_func
#' @export
linker_info_db <- function(bond_ISIN,
                           projected_inflation_curve,
                           real_price =  NULL,
                           real_yield =  NULL,
                           ref_date = Sys.Date(),
                           lm_database_path = rmlmdbpath,
                           infl_database_path = rminfldbpath){
  
  if(is.null(real_yield) == is.null(real_price)){futile.logger::flog.error("One and only one of real_yield and 
                                                                           real_price can be defined. Please change one to NULL")}
  
  if (!is.character(infl_database_path) | !file.exists(infl_database_path)){
    futile.logger::flog.error('inflation database path file path not found or is in the wrong format')
  }
  
  if (!is.character(lm_database_path) | !file.exists(lm_database_path)){
    futile.logger::flog.error('list membership database path file path not found or is in the wrong format')
  }
  
  if (!is.character(bond_ISIN)){
    futile.logger::flog.error('bond_ISIN must be a character string, e.g. "US912828Q608"')
  }
  
  if (!lubridate::is.Date(ref_date)){
    futile.logger::flog.error('Reference date not in correct format, must be in format YYYY-MM-DD')
  }
  
  linker_static <- InflationTools::linker_static_db(bond_ISIN = bond_ISIN,
                                                    lm_database_path = lm_database_path,
                                                    infl_database_path = infl_database_path)
  
  info <- InflationTools::linker_info(real_yield = real_yield,
                      real_price = real_price,
                      projected_inflation_curve = projected_inflation_curve,
                      reference_cpi = linker_static$reference_cpi,
                      inflation_lag = linker_static$inflation_lag,
                      maturity_date = linker_static$MaturityDate,
                      coupon = linker_static$coupon,
                      payment_frequency = linker_static$payment_frequency,
                      ref_date = ref_date,
                      settle_convention = linker_static$settle_convention,
                      day_count = linker_static$day_count,
                      principal_floor = linker_static$principal_floor,
                      coupon_floor = linker_static$coupon_floor)
  
  return(info)
  
}

#' @rdname linker_info_func
#' @export
linker_info_price <- function(real_price,
                              projected_inflation_curve,
                              reference_cpi,
                              inflation_lag,
                              principal_floor,
                              coupon_floor,
                              maturity_date,
                              coupon,
                              payment_frequency,
                              ref_date = Sys.Date(),
                              settle_convention = 1,
                              day_count = "ACT/ACT"){
  
  if(ref_date >= maturity_date){
    futile.logger::flog.error("Reference date is after maturity")
    return(list())
  }
  
  cashflow_table <- InflationTools::cashflow_table(maturity_date = maturity_date,
                                                   coupon = coupon,
                                                   payment_frequency = payment_frequency,
                                                   ref_date = ref_date,
                                                   settle_convention = settle_convention,
                                                   day_count = day_count)
  
  linker_cashflow_table <- InflationTools::linker_cashflow_table(cashflow_table = cashflow_table,
                                                                 projected_inflation_curve = projected_inflation_curve,
                                                                 reference_cpi = reference_cpi,
                                                                 ref_date = ref_date,
                                                                 settle_convention = settle_convention,
                                                                 inflation_lag = inflation_lag,
                                                                 principal_floor = principal_floor,
                                                                 coupon_floor = coupon_floor)
  
  real_accrued <- InflationTools::real_accrued(cashflow_table)
  
  real_yield <-  InflationTools::real_yield(cashflow_table, 
                                            real_price,
                                            payment_frequency,
                                            real_accrued)
  
  current_index_value <- InflationTools::interpolate_inflation_curve(projected_inflation_curve,
                                                                     ref_date = ref_date,
                                                                     inflation_lag = inflation_lag,
                                                                     settle_convention = settle_convention,
                                                                     round_5 = TRUE)
  
  current_index_ratio <- round((current_index_value / reference_cpi), 5)
  
  actual_accrued <- real_accrued * current_index_ratio
  
  principal <- (real_price *  current_index_ratio * 10000)
  
  proceeds <- principal + actual_accrued
  
  output_cashflow_table <- linker_cashflow_table %>%
    dplyr::select(cashflow_date, adjusted_cashflow) %>%
    dplyr::rename(date = cashflow_date,
                  cashflow = adjusted_cashflow)
  
  
  
  real_yield_sa <- InflationTools::seasonally_adjusted_real_yield(linker_cashflow_table,
                                                                  real_price,
                                                                  payment_frequency,
                                                                  real_accrued)
  
  nominal_yield <- InflationTools::nominal_equivalent_yield(linker_cashflow_table,
                                                            real_price,
                                                            payment_frequency,
                                                            real_accrued, 
                                                            principal)
  
  mac_dur <- InflationTools::duration_mac_inflation(linker_cashflow_table,
                                                    real_yield,
                                                    payment_frequency)
  
  mod_dur <- mac_dur / (1 + (real_yield / (payment_frequency * 100)))
  
  dv01_nom <- (mod_dur * real_price)  
  
  dv01_inf <- dv01_nom * current_index_ratio
  
  convexity <- InflationTools::convexity_inflation(linker_cashflow_table,
                                                   real_yield,
                                                   payment_frequency)
  
  inflation_to_mat <- ((linker_cashflow_table$proj_infl[nrow(linker_cashflow_table)] / current_index_value) ^ 
                         (payment_frequency / linker_cashflow_table$discount_period_fraction[nrow(linker_cashflow_table)])
                       ) - 1  
  
  ie01 <- mac_dur * real_price * (1 / (1 + inflation_to_mat))
  
  output_list <- list(real_yield_nsa = real_yield,
                      real_yield_sa = real_yield_sa,
                      real_price = real_price,
                      nominal_equivalent_yield = nominal_yield,
                      real_accured =  real_accrued %>% round(2),
                      actual_accrued = actual_accrued %>% round(2),
                      principal = principal %>% round(2),
                      proceeds = proceeds %>% round(2),
                      current_index_value = current_index_value,
                      current_index_ratio = current_index_ratio,
                      cashflows = output_cashflow_table,
                      macaulay_duration = mac_dur,
                      modified_duration = mod_dur,
                      dv01_nom = dv01_nom,
                      dv01_inf = dv01_inf,
                      convexity = convexity,
                      ie01 = ie01)
  
  return(output_list)
  
}

