

#' Find the index value on a given day
#'
#' @param projected_inflation_curve  data.table, curve of projected inflation with columns \code{date} and \code{proj_infl},
#'     eg can be generated by \link[InflationTools]{implied_proj_inflation_curve}
#' @param ref_date date, the expected trade date, default to today
#' @param inflation_lag numeric, the lag in months that instrument has to the inflation index 
#' @param settle_convention numeric, the days until the instrument will be settled
#' @param round_5 logical, whether the index value should be rounded to five decimal places
#'
#' @return numeric, the interpolated index value for ref_date
#' @export 
#' @importFrom lubridate %m+%
#' @examples
#' 
#' interpolate_inflation_curve(exampleUSInflationCurve, 
#'                             ref_date = as.Date("2021-05-01"),
#'                             inflation_lag = 3)
#' 
#' 
interpolate_inflation_curve <- function(projected_inflation_curve,
                                        ref_date = Sys.Date(),
                                        inflation_lag = 3,
                                        settle_convention = 1,
                                        round_5 = TRUE,
                                        interpolation = "daily"){
  
  if(!(interpolation %in% c("daily", "monthly"))){
    futile.logger::flog.error(paste0(interpolation, " interpolation method not supported can be monthly or daily."))
  }
  
  # lag the inflation curve
  projected_inflation_curve <- InflationTools::lag_inflation_curve(inflation_curve = projected_inflation_curve,
                                                                   inflation_lag = inflation_lag)
  
  # interpolate based on interpolation method choice
  if(interpolation == "daily"){
    y_val <- stats::approx(x = projected_inflation_curve$date, 
                           y = projected_inflation_curve$proj_infl, 
                           xout = ref_date + settle_convention)$y
  }else if(interpolation == "monthly"){
    y_val <- stats::approx(x = projected_inflation_curve$date, 
                           y = projected_inflation_curve$proj_infl,
                           xout = as.Date(paste(
                             lubridate::year(input),
                             lubridate::month(input),
                             "01",
                             sep = "-"
                           )))$y
  }
  
  
  if(round_5 == TRUE){y_val <- round(y_val, 5)}
  
  return(y_val)
  
}

#' Lag the inflation curve by a number of months
#' 
#' @description Lags an inflation curve by a set number of months. In inflation calculations the end month inflation value is
#'     used as the value for the first day of the month. So a three month lag is more like a two month and one day lag. 
#'
#' @param projected_inflation_curve  data.frame, curve of projected inflation with columns \code{date} and \code{proj_infl},
#'     eg can be generated by \link[InflationTools]{implied_proj_inflation_curve}
#' @param inflation_lag numeric, the lag in months that instrument has to the inflation index 
#'
#' @return data.frame, the input data.frame with a changed date column to reflect the relevant lag
#' 
#' @export 
#' @importFrom lubridate %m+%
#' @examples
#' 
#' lag_inflation_curve(exampleUSInflationCurve, 
#'                             inflation_lag = 3)
#' 
#' 
lag_inflation_curve <- function(inflation_curve,
                                inflation_lag = 3){
  
  inflation_curve["date"] <- (inflation_curve[["date"]] + 1)  %m+% months(inflation_lag - 1) 
  
  return(inflation_curve)
  
}


